### ISSUE TITLE
Elección de licencias

### ISSUE THREAD

**Issue by jrgonzalezg** [PabloCastellano/libreborme#32]
Antes que nada, decir que el proyecto me parece una gran iniciativa y una forma de democratizar el acceso a información sobre empresas para todos los ciudadanos, así que ya sólo con la existencia de la web de LibreBORME creo que se ha conseguido un gran aporte para la sociedad.

No obstante, me gustaría saber si contemplas la opción de cambiar las licencias del proyecto a algunas que no sean tan restrictivas como la AGPL (libreborme) o la GPL (bormeparser). En mi caso particular, también en el pasado liberé algún código con este tipo de licencias, sobre todo por recomendación de las Oficinas de Software Libre (OSL) de las universidades en las que he estado. Pero con el tiempo he llegado a la conclusión de que este tipo de licencias son un error ya que restringen las libertades sobre el uso del proyecto y eso hace mucho más difícil que puedan colaborar terceros que no puedan aceptar dichas condiciones, como pueden ser las empresas privadas. En general, todos los proyectos libres que uso o en los que colaboro, ahora que estoy vinculado a una empresa ([Quadbits](http://www.quadbits.com)), son siempre con licencia MIT / BSD o Apache, ya que las condiciones de las AGPL / GPL hacen que sea complicado su uso en la mayoría de proyectos. Algunas razones de por qué este tipo de licencias no son las mejores para liberar software se pueden ver, por ejemplo, aquí: http://www.linuxjournal.com/article/5935, http://www.cnet.com/news/apache-better-than-gpl-for-open-source-business/. Y como ejemplo de proyectos open source con gran éxito gracias, además de a su calidad, a que usan licencias más permisivas como la MIT / BSD o la Apache, no hay más que ver los que hace Google (https://github.com/google) o Square (https://github.com/square/), que son casos especialmente destacados por el gran número de desarrolladores que los utilizan. Entre estos proyectos, uno especialmente interesante es Dagger (https://github.com/square/dagger, https://github.com/google/dagger), con multitud de usuarios y contribuidores, y el liderazgo compartido y alternativo de Square y Google a lo largo del tiempo, que sin la licencia Apache hubiera sido del todo imposible. Y por último, también destacar que Google tiene incluso expresamente baneada la AGPL para uso interno: http://www.theregister.co.uk/2011/03/31/google_on_open_source_licenses/

Así, pues, mi pregunta es si la elección de licencias que has hecho es susceptible de cambiarse por otras más permisivas o si están elegidas de este modo por alguna razón de peso. Un saludo!

**Comment by juanfra684** [comment]
Solo un comentario sobre la licencia de bormeparse. Si usas una licencia GPLv3+ para una librería, los proyectos que son GPLv2 (es decir los que no son GPLv2+) no podrían usarla.
