### ISSUE TITLE
API JSON

### ISSUE THREAD

**Issue by martgnz** [PabloCastellano/libreborme#35]
Es posible sacar los datos en JSON a partir de consultas?

**Comment by PabloCastellano** [comment]
Puedes echarle un ojo a la documentación de la API aquí:
https://libreborme.readthedocs.org/es/latest/api/

Por favor, no uses los issues de github como un foro. Si son dudas mejor escríbelas a contacto@libreborme.net (para la próxima ;)). Gracias!

**Comment by martgnz** [comment]
Hey, perdona, no alcancé a ver la documentación.

Gracias!
