### ISSUE TITLE
Error guardar XML en ruta inexistente - borme.py

### ISSUE THREAD

**Issue by j6e** [PabloCastellano/libreborme#48]
Tras una ejecución interrumpida de script.sh lo vuelvo a lanzar y lo siguiente aparece:

> Está accediendo un archivo BORME XML no definitivo
> Está accediendo un archivo BORME XML no definitivo
> /usuario/.bormes/xml/2017/06/BORME-S-20170601.xml
> Está guardando un archivo no definitivo
> 
> Ran import_borme_download at 2017-06-01 08:39:20.497295+00:00
>   Import date: 2017-06-01. Section: A
> 
> 
> PATH: /usuario/.bormes/pdf/2017/06/01
> DATE: 2017-06-01
> SECCION: A
> 
> BORME-A-2017-102-45.pdf already exists!
> BORME-A-2017-102-22.pdf already exists!
> BORME-A-2017-102-05.pdf already exists!
> BORME-A-2017-102-50.pdf already exists!
> BORME-A-2017-102-02.pdf already exists!
> BORME-A-2017-102-16.pdf already exists!
> BORME-A-2017-102-17.pdf already exists!
> BORME-A-2017-102-08.pdf already exists!
> BORME-A-2017-102-04.pdf already exists!
> BORME-A-2017-102-33.pdf already exists!
> BORME-A-2017-102-12.pdf already exists!
> BORME-A-2017-102-29.pdf already exists!
> BORME-A-2017-102-39.pdf already exists!
> BORME-A-2017-102-06.pdf already exists!
> BORME-A-2017-102-47.pdf already exists!
> BORME-A-2017-102-13.pdf already exists!
> BORME-A-2017-102-41.pdf already exists!
> BORME-A-2017-102-44.pdf already exists!
> BORME-A-2017-102-36.pdf already exists!
> BORME-A-2017-102-48.pdf already exists!
> BORME-A-2017-102-18.pdf already exists!
> BORME-A-2017-102-03.pdf already exists!
> BORME-A-2017-102-46.pdf already exists!
> BORME-A-2017-102-51.pdf already exists!
> BORME-A-2017-102-43.pdf already exists!
> BORME-A-2017-102-30.pdf already exists!
> BORME-A-2017-102-21.pdf already exists!
> BORME-A-2017-102-35.pdf already exists!
> BORME-A-2017-102-07.pdf already exists!
> BORME-A-2017-102-11.pdf already exists!
> BORME-A-2017-102-28.pdf already exists!
> BORME-A-2017-102-99.pdf already exists!
> 
> BORMEs creados: 0/0
> Anuncios creados: 0/0
> Empresas creadas: 0/0
> Personas creadas: 0/0
> Total elapsed time: 0.08 seconds
> Está accediendo un archivo BORME XML no definitivo
> 
> Traceback (most recent call last):
>   File "./manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usuario/Envs/libreborme/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usuario/Envs/libreborme/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usuario/Envs/libreborme/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usuario/Envs/libreborme/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
>     output = self.handle(*args, **options)
>   File "/var/www/libreborme/borme/management/commands/importbormetoday.py", line 25, in handle
>     update_previous_xml(date)
>   File "/var/www/libreborme/borme/importer.py", line 257, in update_previous_xml
>     prev_bxml.save_to_file(prev_xml_path)
>   File "/usuario/Envs/libreborme/lib/python3.5/site-packages/bormeparser/borme.py", line 397, in save_to_file
>     self.xml.write(path, encoding='iso-8859-1', pretty_print=True)
>   File "src/lxml/lxml.etree.pyx", line 2033, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:63707)
>   File "src/lxml/serializer.pxi", line 512, in lxml.etree._tofilelike (src/lxml/lxml.etree.c:134950)
>   File "src/lxml/serializer.pxi", line 571, in lxml.etree._create_output_buffer (src/lxml/lxml.etree.c:135614)
>   File "src/lxml/serializer.pxi", line 560, in lxml.etree._create_output_buffer (src/lxml/lxml.etree.c:135415)
> FileNotFoundError: [Errno 2] No such file or directory

Me he puesto en modo debug y he printeado la variable path antes de que salte la excepcion:

> /usuario/.bormes/xml/2017/05/BORME-S-20170531.xml 

El problema es que el directorio /usuario/.bormes/xml/2017/05/ no existe, solo existe el /06.
El programa lo he ejecutado por primera vez hoy 01/06/2017, entiendo que tengo un archivo que es de fecha de ayer pero la carpeta del mes pasado no está creda. 

¿Quizá se debería añadir una comprobación de que el directorio existe antes de intentar escribir en él?

Creando el directorio manualmente el script finaliza sin problemas.

**Comment by PabloCastellano** [comment]
Nunca se me había dado el caso. Gracias por reportarlo.

> ¿Quizá se debería añadir una comprobación de que el directorio existe antes de intentar escribir en él?

Definitivamente sí.

**Comment by PabloCastellano** [comment]
Arreglado con https://github.com/PabloCastellano/bormeparser/pull/12

Gracias!
