### ISSUE TITLE
urllib.error.ContentTooShortError en download.py

### ISSUE THREAD

**Issue by j6e** [PabloCastellano/libreborme#49]
Llevo varios días investigando un error bastante recurrente y a la vez esquivo:

> Exception in thread Thread-77:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/borme/.virtualenvs/libreborme/lib/python3.5/site-packages/bormeparser/download.py", line 384, in run
    downloaded = download_url(url, full_path)
  File "/home/borme/.virtualenvs/libreborme/lib/python3.5/site-packages/bormeparser/download.py", line 299, in download_url
    local_filename, headers = request.urlretrieve(url, filename)
  File "/usr/lib/python3.5/urllib/request.py", line 229, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 359440 out of 1454465 bytes>

No he conseguido averiguar si se debe a alguna condición de carrera especial o es un error de pérdida de paquetes o similar (mi apuesta personal). 

Tengo funcionando un apaño, capturando la excepción e intentando un ciclo de 3 reintentos y no he vuelto a tener el fallo. Si no lo consigo replicar de nuevo, hago un pull request.

**Comment by PabloCastellano** [comment]
Yo también he visto este error desde hace un tiempo pero no he tenido tiempo de investigarlo.
Parece un error por parte del servidor y no sé si tiene que ver con usar https pero definitivamente debería de ser un caso controlado, así que tu PR es bienvenido :grinning:

**Comment by PabloCastellano** [comment]
Arreglado con https://github.com/PabloCastellano/bormeparser/pull/12

Gracias!
