### ISSUE TITLE
Certificado Caducado

### ISSUE THREAD

**Issue by rafaelbn** [PabloCastellano/libreborme#50]
Hola @PabloCastellano :

Al entrar en https://libreborme.net no deja por el certificado y no permite añadir una excepción en el navegador: 

> Su conexión no es segura

> libreborme.net usa un certificado de seguridad no válido. El certificado está caducado desde lunes, 30 de julio de 2018 1:25:26. La fecha y hora actual es 1 de agosto de 2018 10:56. Código de error: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by PabloCastellano** [comment]
Gracias por el aviso! Ya está arreglado y he puesto los medios necesarios para que no vuelva a pasar.

**Comment by rafaelbn** [comment]
¡Genial @PabloCastellano muchísimas gracias! Mira a ver si me puedes aceptar en Linkedin :smile:
