### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by zidingz** [PabloCastellano/libreborme#62]
Hey there!

I belong to an open source security research community, and a member (@dig2) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by PabloCastellano** [comment]
Hello @zidingz. This repo contains the source code for an obsolete version of the website.

To the best of my knowledge it is not running anywhere online. Feel free to disclose the issue here or to `contacto AT libreborme.net`

**Comment by JamieSlome** [comment]
@PabloCastellano - here is the report for your reference:

https://huntr.dev/bounties/fbefb41c-4bf7-4234-9ab1-df1d04e9ca43/
